# Variable Group 'grocery-list' was defined in the Variables tab
variables:
- group: grocery-list
- name: buildTag
  value: $(Build.SourceBranchName).$(Build.BuildId)
- name: BuildParameters.dockerFile
  value: '**/Dockerfile'
- name: isDevelop
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
- name: isDevOps
  value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/devops/')]
- name: isPR
  value: $[eq(variables['Build.Reason'], 'PullRequest')]

resources:
  pipelines:
  - pipeline: grocery-shop-service
    source: grocery-shop-service
    trigger:
      branches:
        include:
        - refs/heads/develop

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:

- stage: Utests_N_Build
  condition: and(eq(variables.isPR, 'true'), eq(variables.isDevelop, 'false'))
  displayName: 'Run unite tests, code scan and build image'

  jobs:
  - job: Build
    displayName: Utests_N_Build job
    pool: Default

    steps:
    - checkout: self

    - task: Docker@0
      displayName: Build an image
      inputs:
        action: Run a Docker command
        dockerFile: $(BuildParameters.dockerFile)
        customCommand: build --target build --build-arg SONAR_TOKEN=$(SONAR_TOKEN) -t gr-list-back-test .

    - task: Docker@0
      displayName: Clean unuses images
      inputs:
        action: Run a Docker command
        customCommand: image rm gr-list-back-test -f

- stage: Build_N_Push
  condition: eq(variables.isDevelop, 'true')
  displayName: 'Run build and push image to ACR'

  jobs:
  - job: Build
    displayName: Build_N_Push job
    pool: Default
 
    steps:
    - checkout: self

    - task: Docker@0
      displayName: Build an image
      inputs:
        azureSubscriptionEndpoint: 38386be4-ac4e-425b-8cd7-0127b8f9c0d9
        azureContainerRegistry: '{"loginServer":"mddinternship2021h2project.azurecr.io", "id" : "/subscriptions/01145a00-1779-4383-8b3a-08a39e3816fe/resourceGroups/Internship/providers/Microsoft.ContainerRegistry/registries/mddinternship2021h2project"}'
        dockerFile: $(BuildParameters.dockerFile)
        buildArguments: SONAR_TOKEN=$(SONAR_TOKEN)
        imageName: grocery-shop-service
        additionalImageTags: $(buildTag)

    - task: Docker@0
      displayName: Push an image
      inputs:
        azureSubscriptionEndpoint: 38386be4-ac4e-425b-8cd7-0127b8f9c0d9
        azureContainerRegistry: '{"loginServer":"mddinternship2021h2project.azurecr.io", "id" : "/subscriptions/01145a00-1779-4383-8b3a-08a39e3816fe/resourceGroups/Internship/providers/Microsoft.ContainerRegistry/registries/mddinternship2021h2project"}'
        action: Push an image
        imageName: grocery-shop-service
        additionalImageTags: $(buildTag)

    - task: Docker@0
      displayName: Clean unuses images
      inputs:
        action: Run a Docker command
        customCommand: image rm grocery-shop-service:$(buildTag) -f

    - task: Docker@0
      displayName: Clean dangling images
      inputs:
        action: Run a Docker command
        customCommand: image prune -f

- stage: Deploy2dev
  dependsOn: Build_N_Push
  condition: and(succeeded('Build_N_Push'), eq(variables.isDevelop, 'true'))
  displayName: Deploy to AKS dev

  jobs:
    - job: Deploy
      displayName: Deploy to dev-AKS job
      pool: Default
      
      steps:
      - checkout: self
      - task: KubernetesManifest@0
        displayName: deploy
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'grocery-list-dev-sc'
          namespace: 'grocery-list-dev'
          manifests: manifests/dev-deployment.yml
          containers: mddinternship2021h2project.azurecr.io/grocery-shop-service:$(buildTag)

- stage: Deploy2demo
  dependsOn: Deploy2dev
  condition: and(succeeded('Deploy2dev'), eq(variables.isMain, 'true'))
  displayName: Deploy to AKS demo

  jobs:

    - job: Validation 
      displayName: Manual validation job
      pool: server
      timeoutInMinutes: 1440

      steps:
      - task: ManualValidation@0
        displayName: Manual Validation
        retryCountOnTaskFailure: 1
        timeoutInMinutes: 120
        inputs:
          notifyUsers: |
            nicolae.nicolaev@endava.com
            vitali.maximov@endava.com
          instructions: Please review and approve the backend release

    - job: Deploy
      displayName: Deploy to demo-AKS job
      dependsOn: Validation
      pool: Default
      
      steps:
      - checkout: self
      - task: KubernetesManifest@0
        displayName: deploy
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'grocery-list-demo-sc'
          namespace: 'grocery-list-demo'
          manifests: manifests/demo-deployment.yml
          containers: mddinternship2021h2project.azurecr.io/grocery-shop-service:$(buildTag)

      - task: Kubernetes@1
        displayName: check demo deployment status 
  
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'grocery-list-demo-sc'
          namespace: 'grocery-list-demo'
          command: 'rollout'
          arguments: 'status deployment/grocery-shop-service'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'
          azureSubscriptionEndpointForSecrets: 'MDDInternship_GroceryList'
          azureContainerRegistry: 'mddinternship2021h2project.azurecr.io'
          forceUpdate: false
  
      - task: Kubernetes@1
        displayName: rollback to previous version
        condition: failed()
  
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'grocery-list-demo-sc'
          namespace: 'grocery-list-demo'
          command: 'rollout'
          arguments: 'undo deployment/grocery-shop-service'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'
          azureSubscriptionEndpointForSecrets: 'MDDInternship_GroceryList'
          azureContainerRegistry: 'mddinternship2021h2project.azurecr.io'
          forceUpdate: false
  