

variables:
- group: grocery-list
- name: BuildParameters.dockerFile
  value: '**/Dockerfile'
  vImageName: ubuntu-18.04

resources:
  pipelines:
  - pipeline: grocery-shop-service
    source: grocery-shop-service
    trigger:
      branches:
        include:
        - refs/heads/develop

name: $(Build.SourceVersion)$(rev:.r)

stages:
- stage: UTests
  displayName: 'Run unite tests and code scan'
  dependsOn: string
  condition: string
  jobs: 
  - job: 'UTests'
    displayName: 'Unite tests job '
    pool:
      vmImage: $(vImageName)
    steps:
  - checkout: self
  - task: Docker@0
    displayName: Build an image
    inputs:
      dockerFile: $(BuildParameters.dockerFile)
      # arguments: --target sonarscan
      buildArguments: SONAR_TOKEN=$(SONAR_TOKEN)
      command: build
      target: sonarscan

- stage: Build-N-Push
  displayName: 'Run build and push image to ACR'
  
  jobs:
  - job: Build
    displayName: Build-N-Push job
    pool:
      vmImage: $(vImageName)
    steps:
    - checkout: self

    - task: Docker@0
      displayName: Build an image
      inputs:
        azureSubscriptionEndpoint: 38386be4-ac4e-425b-8cd7-0127b8f9c0d9
        azureContainerRegistry: '{"loginServer":"mddinternship2021h2project.azurecr.io", "id" : "/subscriptions/01145a00-1779-4383-8b3a-08a39e3816fe/resourceGroups/Internship/providers/Microsoft.ContainerRegistry/registries/mddinternship2021h2project"}'
        dockerFile: $(BuildParameters.dockerFile)
        buildArguments: SONAR_TOKEN=$(SONAR_TOKEN)

    - task: Docker@0
      displayName: Push an image
      inputs:
        azureSubscriptionEndpoint: 38386be4-ac4e-425b-8cd7-0127b8f9c0d9
        azureContainerRegistry: '{"loginServer":"mddinternship2021h2project.azurecr.io", "id" : "/subscriptions/01145a00-1779-4383-8b3a-08a39e3816fe/resourceGroups/Internship/providers/Microsoft.ContainerRegistry/registries/mddinternship2021h2project"}'
        action: Push an image

- stage: DeployToDev
  displayName: 'Deployment to dev environment'
  
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: ubuntu-18.04
    steps:
    - checkout: self
      