INSERT INTO t_items (id,
                     product_id,
                     quantity,
                     size,
                     email)
VALUES (NEXT VALUE FOR grocery_shop_sequence,
             (SELECT id FROM t_products WHERE name = 'Avocado'),
             2,
             2,
             'user@endava.com'),
       (NEXT VALUE FOR grocery_shop_sequence,
             (SELECT id FROM t_products WHERE name = 'Garlic'),
             2,
             3,
             'user@endava.com');