INSERT INTO t_products (
    id,
    description,
	image_url,
	name,
	price,
	rating,
	size_type
)
VALUES
	(NEXT VALUE FOR grocery_shop_sequence,
	'A very tasty watermelon.',
	'https://e1.pngegg.com/pngimages/832/291/png-clipart-fruit-sliced-watermelon.png',
	'Watermelon',
	3.5,
	4.8,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Fresh ostrich eggs.',
	'https://img.favpng.com/10/7/0/yellow-material-circle-egg-png-favpng-keVjqZyvV6E9K8S1XDMaQmbHX_t.jpg',
	'Ostrich eggs',
	60,
	3.2,
	'PACKS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Ripe avocado.',
	'https://esquilo.io/png/thumb/LnvAaipm58NPh4I-Avocado-PNG-Photo.png',
	'Avocado',
	16,
	5,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Smelly garlic to scare vampires',
	'https://w7.pngwing.com/pngs/687/273/png-transparent-garlics-garlic-organic-food-cooking-vegetable-herb-garlic-food-onion-vegetables.png',
	'Garlic',
	6,
	2.3,
	'PACKS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Small and round tomatoes with sweet taste.',
	'https://toppng.com/uploads/preview/wallpaper-popular-full-ultra-cherry-tomatoes-transparent-11563266951sjfpnofhvt.png',
	'Cherry tomato',
	13.75,
	3.6,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'The nut from the palm tree.',
	'https://toppng.com/uploads/preview/coconut-11528344888voecrc9r6f.png',
	'Coconut',
	16.7,
	4.7,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Perfect organic rice to make your favourite pilaf.',
	'https://w7.pngwing.com/pngs/801/821/png-transparent-white-rice-basmati-jasmine-rice-plant-milk-rice-food-breakfast-cereal-rice.png',
	'Rice',
	8.43,
	3.9,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'The best turkeys, risen on free-range farms.',
	'https://img.favpng.com/13/14/7/turkey-meat-food-cooking-roasting-png-favpng-cwuWGTt8TwLkLfKUQvRqy4v8D.jpg',
	'Turkey meat',
	25.5,
	4.1,
	'PACKS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'A leaf vegetable appreciated for its fresh, tart, bitter, and peppery flavor.',
	'https://w7.pngwing.com/pngs/187/664/png-transparent-arugula-lettuce-leaf-vegetable-salad-endive-rucola-leaf-spinach-superfood.png',
	'Rocket',
	6.3,
	4.0,
	'PACKS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Orange veggie.',
	'https://w7.pngwing.com/pngs/785/652/png-transparent-carrot-vegetable-health-food-nutrition-carrots-food-orange-nutrition.png',
	'Carrot',
	8.9,
	2.9,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Onions high in fiber and flavonoids.',
	'https://e7.pngegg.com/pngimages/298/73/png-clipart-red-onion-vegetable-onion-recipe-onion.png',
	'Red onion',
	9.4,
	3.8,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Edible mushrooms.',
	'https://icon2.cleanpng.com/20180408/coq/kisspng-common-mushroom-edible-mushroom-food-fungus-mushroom-5aca3e716c6924.4306075115232036974441.jpg',
	'White champignon',
	48.6,
	3.4,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'The. Best. Vegetable. EVA.',
	'https://www.pikpng.com/pngl/m/21-210593_eggplant-png-file-aubergine-png-clipart.png',
	'Eggplant',
	5.6,
	5,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Ripe mango.',
	'https://e7.pngegg.com/pngimages/840/192/png-clipart-fruit-fruit-mango.png',
	'Mango',
	67.6,
	2.6,
	'PACKS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Autumn fruit.',
	'https://w7.pngwing.com/pngs/620/798/png-transparent-asian-pear-fruit-williams-pear-avocado-grocery-store-avocado-dried-fruit-food-asian-pear.png',
	'Pear',
	19.8,
	4.6,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'South East Asian fruit.',
	'https://w7.pngwing.com/pngs/203/1019/png-transparent-sliced-dragon-fruit-juice-hylocereus-undatus-hylocereus-megalanthus-pitaya-fruit-durian-natural-foods-food-nutrition-thumbnail.png',
	'Dragon fruit',
	79.99,
	4.7,
	'PACKS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Manually picked blackberries.',
	'https://w7.pngwing.com/pngs/822/561/png-transparent-three-blackberries-blackberry-fruit-blackberry-natural-foods-food-mulberry-thumbnail.png',
	'Blackberry',
	120.6,
	4.6,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Eye-saving berry.',
	'https://e7.pngegg.com/pngimages/560/864/png-clipart-blueberries-blueberries.png',
	'Blueberry',
	235.0,
	3.6,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Sweet apricots.',
	'https://c.neh.tw/thumb/f/720/comdlpng6960652.jpg',
	'Apricot',
	20.45,
	3.7,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Soft peaches.',
	'https://cdn.imgbin.com/20/15/2/imgbin-nectar-juice-dried-fruit-peaches-and-cream-juice-WXCJkLQHkiBJLZGXvzPFReKWN.jpg',
	'Peach',
	46.8,
	4.5,
	'KILOS'),
	(NEXT VALUE FOR grocery_shop_sequence,
	'Violet organic plums.',
	'https://www.vhv.rs/dpng/d/546-5469860_plum-transparent-background-hd-png-download.png',
	'Plum',
	6.8,
	4.2,
	'KILOS');

