INSERT INTO t_products (id,
                        description,
                        image_url,
                        name,
                        price,
                        rating,
                        size_type)
VALUES (NEXT VALUE FOR grocery_shop_sequence,
             'A very tasty broccoli.',
             'https://i.imgur.com/vnOJdKE.jpg',
             'Broccoli',
             3.15,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Fresh cauliflower',
             'https://i.imgur.com/B6VPuQx.jpg',
             'Cauliflower',
             65,
             null,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Exceptional celery',
             'https://i.imgur.com/DLxr2qB.jpg',
             'Celery',
             162,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Tasty cherries',
             'https://i.imgur.com/E7w3Pja.jpg',
             'Cherries',
             61,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Fresh ginger',
             'https://i.imgur.com/dxiGBep.jpg',
             'Ginger',
             17.75,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Fresh grapefruits',
             'https://i.imgur.com/yQkHBea.jpg',
             'Grapefruit',
             4.7,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Sweet red grapes',
             'https://i.imgur.com/VewnSBJ.jpg',
             'Red grapes',
             31.43,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Fresh guavas',
             'https://i.imgur.com/gHvtIxK.jpg',
             'Guava',
             22.5,
             null,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'The best kiwi in the world',
             'https://i.imgur.com/Wli9Hnd.jpg',
             'Kiwi',
             62.3,
             null,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Sweet Orange',
             'https://i.imgur.com/zGAKuz1.png',
             'Orange',
             28.9,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Tiny peas',
             'https://i.imgur.com/9fwBKKn.jpg',
             'Peas',
             19.4,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Giant red peppers',
             'https://i.imgur.com/5bZP5i0.jpg',
             'Red peppers',
             48.6,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Fresh pineapple',
             'https://i.imgur.com/UJvidxd.png',
             'Pineapple',
             3.2,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Fresh radish',
             'https://i.imgur.com/i39ltG0.jpg',
             'Radish',
             61.6,
             null,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Tasty raisins',
             'https://i.imgur.com/bGQ5QPU.jpg',
             'Raisins',
             2.8,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'South East Spinach',
             'https://i.imgur.com/Vlmgs0c.jpg',
             'Spinach',
             22,
             null,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Sweetest strawberries',
             'https://i.imgur.com/Mj9ir01.jpg',
             'Strawberries',
             3.6,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Giant Watermelon',
             'https://i.imgur.com/VocivbJ.jpg',
             'Watermelon',
             235.0,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Giant walnuts',
             'https://i.imgur.com/Y0b9xim.jpg',
             'Walnuts',
             215,
             null,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Really really good white onnions',
             'https://i.imgur.com/gDzwv7L.jpg',
             'White onions',
             43,
             null,
             'KILOS');