INSERT INTO t_addresses (user_email,
                         address_email,
                         address,
                         apartment,
                         first_name,
                         last_name)
VALUES ('admin@endava.com',
        'admin@endava.com',
        'MD, Chisinau, str. Pictor Ion Jumati, 6',
        null,
        'Nicolae',
        'Nicolaev'),
       ('user@endava.com',
        'user@endava.com',
        'MD, Chisinau, str. Stefan cel Mare si Sfant 171/3',
        '141',
        'Vitali',
        'Butnar');