INSERT INTO t_products (id,
                        description,
                        image_url,
                        name,
                        price,
                        rating,
                        size_type)
VALUES (NEXT VALUE FOR grocery_shop_sequence,
             'A very tasty watermelon.',
             'https://www.seeds-gallery.shop/5488-large_default/400-watermelon-seeds-crimson-sweet.jpg',
             'Watermelon',
             3.5,
             4.8,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Fresh ostrich eggs.',
             'https://p2.piqsels.com/preview/113/741/98/ostrich-egg-egg-large-egg-bouquet.jpg',
             'Ostrich eggs',
             60,
             3.2,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Ripe avocado.',
             'https://images.immediate.co.uk/production/volatile/sites/30/2020/02/Avocados-3d84a3a.jpg',
             'Avocado',
             16,
             5,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Smelly garlic to scare vampires',
             'https://inspotshoppe.com/wp-content/uploads/2020/07/61ISKQLF1oL._SL1500_.jpg',
             'Garlic',
             6,
             2.3,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Small and round tomatoes with sweet taste.',
             'https://upload.wikimedia.org/wikipedia/commons/1/10/Tomates_cerises_Luc_Viatour.jpg',
             'Cherry tomato',
             13.75,
             3.6,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'The nut from the palm tree.',
             'https://www.impactgrouphr.com/wp-content/uploads/peach-vs-cocnut-culture-feature.jpg',
             'Coconut',
             16.7,
             4.7,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Perfect organic rice to make your favourite pilaf.',
             'https://st3.depositphotos.com/2120545/i/600/depositphotos_347793921-stock-photo-basmati-rice-white-background-raw.jpg',
             'Rice',
             8.43,
             3.9,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'The best turkeys, risen on free-range farms.',
             'https://5.imimg.com/data5/KB/HG/MV/SELLER-60210025/turkey-meat-500x500.jpg',
             'Turkey meat',
             25.5,
             4.1,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'A leaf vegetable appreciated for its fresh, tart, bitter, and peppery flavor.',
             'https://sc04.alicdn.com/kf/U3e3b218bcc6340baa786be4775e7584dw.jpg',
             'Rocket',
             6.3,
             4.0,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Orange veggie.',
             'https://i.ndtvimg.com/mt/cooks/2014-11/carrots.jpg',
             'Carrot',
             8.9,
             2.9,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Onions high in fiber and flavonoids.',
             'https://inmytum.com/wp-content/uploads/2020/03/turnips-OnionRed.jpg',
             'Red onion',
             9.4,
             3.8,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Edible mushrooms.',
             'https://www.freshpoint.com/wp-content/uploads/commodity-button-mushroom.jpg',
             'White champignon',
             48.6,
             3.4,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'The. Best. Vegetable. EVA.',
             'https://media.healthyfood.com/wp-content/uploads/2016/10/In-season-December-Eggplant-peaches-Thinkstock-462838893.jpg',
             'Eggplant',
             5.6,
             5,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Ripe mango.',
             'https://www.svz.com/wp-content/uploads/2018/05/Mango.jpg',
             'Mango',
             67.6,
             2.6,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Autumn fruit.',
             'https://www.bigbasket.com/media/uploads/p/l/40048444_3-fresho-pear-green-imported.jpg',
             'Pear',
             19.8,
             4.6,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'South East Asian fruit.',
             'https://produits.bienmanger.com/38126-0w470h470_Red_Dragon_Fruit.jpg',
             'Dragon fruit',
             79.99,
             4.7,
             'PACKS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Manually picked blackberries.',
             'https://static.libertyprim.com/files/familles/m%C3%BBre-large.jpg',
             'Blackberry',
             120.6,
             4.6,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Eye-saving berry.',
             'https://cdn.shopify.com/s/files/1/0258/4307/3103/products/asset_31_800x.jpg',
             'Blueberry',
             235.0,
             3.6,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Sweet apricots.',
             'https://befreshcorp.net/wp-content/uploads/2017/07/product-packshot-apricot.jpg',
             'Apricot',
             20.45,
             3.7,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Soft peaches.',
             'https://static.libertyprim.com/files/familles/peche-large.jpg',
             'Peach',
             46.8,
             4.5,
             'KILOS'),
       (NEXT VALUE FOR grocery_shop_sequence,
             'Violet organic plums.',
             'https://frost-line.com/wp-content/uploads/2018/07/frostline_sljiva.jpg',
             'Plum',
             6.8,
             4.2,
             'KILOS');
